[package]
name = "myapp"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
